### PR TITLE
Convert PID gains to 16bit

### PR DESCRIPTION
**Pull request by AllanMar**
Currently using whole int's only. (PIDGAIN_DIV = 1)

Set Max PID Gain UI limit to PIDGAIN_LIM Set to 1024 for now.

### CODE REVIEW

**Comment by mattreba** [comment]
First of all I agree with the need to increase the PID Gains from 8-bit values. If I'm understanding your changes here you are allowing gain values of 0-1024. Is there a reason you are limiting this to a 10-bit value instead of using the full 16-bit variable size?

Also, I've seen other references to PID gains with at least one digit of precision. Should we use the 16-bit variable to represent gain in tenths or hundredths? ie 0.00 - 655.35

**Comment by AllanMar** [comment]
I've been using a version of this on my older BT branch for some time, in that implementation i implented 1 decimal.

When I did this I stuck with INT's as I never ended up setting the gains to anything else. When we switch to PID_V1 which uses a different form of PID gains we'll need 1-2decimals. In the current implentation we need the ability for large I values (>655), and decimals are less important. Decimals are probably important for the D gain, which is not overly important/used in our slow to change systems.

I'm going to fix this up a bit to allow us to easily change (_DIV not quite right) the decimals going forward. So I would say for Beta6 whole INT's are probably best for now, for PID_V1 decimals will be important.

I can't recall why but I seem to recall using a larger max range made it more difficult to enter the values?

**Comment by mattreba** [comment]
Just to be clear :) Should I hold up on merging this in?

**Comment by AllanMar** [comment]
Yea, let me re-look at it later.

**Comment by AllanMar** [comment]
This should be ready. Have a look.

**Pull request merged**
