### PR TITLE
Add Boil Control SETPOINT Mode

### PR DESCRIPTION
**Pull request by AllanMar**
Save boil control mode & boil output for power loss recovery.
Adjust boil screen to display mode  when unlocked. (shift to left)
Boil output is saved every min (only if different), to avoid excessive EEPROM writes when adjusting output.
There are still some issues about transitioning from PID/Manual/RGBIO. Related to #15

I have a bit more testing to do, but have a look @mattreba if you can.

### CODE REVIEW

**Comment by AllanMar** [comment]
There was one part of this i'm not sure of.
When in setpoint mode, moving the encoder on a locked boil screen will revert to manual mode (incase of boil over). The downside to this since i'm resetting the setpoint to boiltemp in manual mode is that you have to go re-enter the setpoint if you accidentally touch the encoder (which is a bit of a pain). Setpoint mode really shouldnt be used near boil temps (perhaps should limit the setpoint?), but i'm not sure which way is better?

**Comment by mattreba** [comment]
Don't reset the setpoint in MANUAL mode. Setpoint should only matter in
setpoint mode. If setpoint is used for other logic in MANUAL or AUTO mode
we should fix that instead.

**Comment by AllanMar** [comment]
That is what I originally tried to implement. But switched back with the issues with shutting off the PID (without changing setpoint, due to the way the PID is implemented/used) and BTPD logic (I personally don't want my BTPD to display 0 when in auto/manual but perhaps that makes more sense). I'll switch the BTPD logic to look at boilcontrolstate and use getboiltemp or setpoint. I suspect your looking at making the BTPD software configurable too and this sort of specific logic will make that more difficult.

I'll go back and try to fix all the issues with not using the setpoint properly (as I do agree). I think I'm going to have to tie this together with a solution for issue #15 to fully address it.

**Comment by AllanMar** [comment]
I think I have the setpoint fully decoupled now. I think the BTPD logic is a bit sloppy this way, but not sure what else to do currently.
No problems so far, still need to test it running programs to make sure there's no surprises.

**Comment by mattreba** [comment]
I would like to rework the BTPD so you can assign a device to the system
and then select a display mode for the device. The setpoint mode will show
the setpoint without consideration for the boil mode but maybe a special
boil control display mode would show something that takes boil control mode
into account.Display modes should be "cheap" and only require a small
amount of program memory.

**Pull request merged**
